version: 2

updates:
  - package-ecosystem: npm
    schedule:
      interval: "monthly"
    directory: /
  - package-ecosystem: github-actions
    schedule:
      interval: "monthly"
    directory: /
